# Generated by Django 3.0.5 on 2020-05-10 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='Followers',
            field=models.ManyToManyField(blank=True, related_name='_profile_Followers_+', to='user.Profile'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Following',
        ),
        migrations.AddField(
            model_name='profile',
            name='Following',
            field=models.ManyToManyField(blank=True, related_name='_profile_Following_+', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='uploads/profile/defaultimage.png', upload_to='uploads/profile/'),
        ),
    ]
